"""add phone number

Revision ID: c660bdb1d99b
Revises: c45abf2574fd
Create Date: 2024-10-02 19:07:07.801483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c660bdb1d99b'
down_revision: Union[str, None] = 'c45abf2574fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_nubmer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_nubmer')
    # ### end Alembic commands ###
